payment_bb_adapter:
  name: "payment-bb-adapter"
  replicaCount: 1
  labels:
    app: "payment-bb-adapter"
  template:
    labels:
      app: "payment-bb-adapter"
  container:
    name: payment-bb-adapter-app
    image: 463471358064.dkr.ecr.eu-central-1.amazonaws.com/bb/payments/adapter:latest
    imagePullPolicy: "Always"
  profiles: "container"
  service:
    name: "payment-bb-adapter"
    type: ClusterIP
    port: 8080
    targetPort: 8080