apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.payment_bb_adapter.name }}
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  serviceName: {{ .Values.payment_bb_adapter.service.name }}
  replicas: {{ .Values.payment_bb_adapter.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.payment_bb_adapter.template.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.payment_bb_adapter.template.labels | nindent 8 }}
    spec:
      initContainers:
        - name: fix-pvc-permissions
          image: busybox
          command: ["sh", "-c"]
          args:
            -
              chmod -R 777 {{ .Values.payment_bb_adapter.dbPersist.mountPath }}
              fi
          env:
          volumeMounts:
            - name: {{ .Values.payment_bb_adapter.dbPersist.volumeMountName }}
              mountPath: {{ .Values.payment_bb_adapter.dbPersist.mountPath }}
      containers:
        - name: {{ .Values.payment_bb_adapter.container.name }}
          image: "{{ .Values.payment_bb_adapter.container.image }}:{{ .Values.payment_bb_adapter.container.imageTag }}"
          imagePullPolicy: {{ .Values.payment_bb_adapter.container.imagePullPolicy }}
          ports:
          - containerPort: 8080
            name: server
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
          env:
            - name: ACTIVE_PROFILES
              value: {{ .Values.payment_bb_adapter.profiles }}
            - name: DATABASE_PERSIST_PATH
              value: {{ .Values.payment_bb_adapter.dbPersist.path }}
          volumeMounts:
            - name: {{ .Values.payment_bb_adapter.dbPersist.volumeMountName }}
              mountPath: {{ .Values.payment_bb_adapter.dbPersist.mountPath }}
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "200m"
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
          name: {{ .Values.payment_bb_adapter.dbPersist.volumeMountName }}
      spec:
          accessModes:
              - ReadWriteOnce
          resources:
              requests:
                  storage: {{ .Values.payment_bb_adapter.dbPersist.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment_bb_adapter.service.name }}-service
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  type: {{ .Values.payment_bb_adapter.service.type }}
  ports:
    - port: {{ .Values.payment_bb_adapter.service.port }}
      targetPort: {{ .Values.payment_bb_adapter.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment_bb_adapter.service.name }}-headless
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.payment_bb_adapter.service.port }}
      targetPort: {{ .Values.payment_bb_adapter.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
