apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.payment_bb_adapter.name }}
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  serviceName: {{ .Values.payment_bb_adapter.service.name }}
  replicas: {{ .Values.payment_bb_adapter.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.payment_bb_adapter.template.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.payment_bb_adapter.template.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.payment_bb_adapter.container.name }}
          image: "{{ .Values.payment_bb_adapter.container.image }}"
          imagePullPolicy: {{ .Values.payment_bb_adapter.container.imagePullPolicy }}
          ports:
          - containerPort: 8080
            name: server
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: server
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: server
          env:
            - name: ACTIVE_PROFILES
              value: {{ .Values.payment_bb_adapter.profiles }}
            - name: PAYMENT_IM_HEADER
              value: {{ .Values.payment_bb_adapter.emulator.header }}
            - name: PAYMENT_IM_BASE_URL
              value: {{ .Values.payment_bb_adapter.emulator.url }}
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "200m"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment_bb_adapter.service.name }}-service
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  type: {{ .Values.payment_bb_adapter.service.type }}
  ports:
    - port: {{ .Values.payment_bb_adapter.service.port }}
      targetPort: {{ .Values.payment_bb_adapter.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment_bb_adapter.service.name }}-headless
  labels:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.payment_bb_adapter.service.port }}
      targetPort: {{ .Values.payment_bb_adapter.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.payment_bb_adapter.labels | nindent 4 }}
