/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.44).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package global.govstack.payment.bb.emulator.controller;

import global.govstack.payment.bb.emulator.dto.InlineResponse200;
import global.govstack.payment.bb.emulator.dto.UpdatebeneficiarydetailsBody;
import io.swagger.annotations.*;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@jakarta.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.SpringCodegen",
    date = "2023-06-02T13:05:58.136949+03:00[Europe/Sofia]")
@Validated
@Api(value = "update-beneficiary-details", description = "the update-beneficiary-details API")
public interface UpdateBeneficiaryDetailsApi {

  @ApiOperation(
      value = "Update beneficiary details",
      nickname = "updateBeneficiaryDetailsPost",
      notes = "",
      response = InlineResponse200.class,
      tags = {})
  @ApiResponses(
      value = {
        @ApiResponse(
            code = 200,
            message = "Successful response",
            response = InlineResponse200.class),
        @ApiResponse(code = 400, message = "Bad request", response = InlineResponse200.class)
      })
  @RequestMapping(
      value = "/update-beneficiary-details",
      produces = {"application/json"},
      consumes = {"application/json"},
      method = RequestMethod.POST)
  ResponseEntity<InlineResponse200> updateBeneficiaryDetailsPost(
      @ApiParam(value = "", required = true) @Valid @RequestBody UpdatebeneficiarydetailsBody body);
}
