apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-server-local
  name: fineract-server-local
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    app: fineract-server
    tier: backend